=== runtipi/appstore/apps/app-config-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "available": {
      "type": "boolean"
    },
    "deprecated": {
      "type": "boolean"
    },
    "exposable": {
      "type": "boolean"
    },
    "no_gui": {
      "type": "boolean"
    },
    "port": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65565
    },
    "https": {
      "type": "boolean"
    },
    "uid": {
      "type": "integer"
    },
    "gid": {
      "type": "integer"
    },
    "force_expose": {
      "type": "boolean"
    },
    "generate_vapid_keys": {
      "type": "boolean"
    },
    "supported_architectures": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "oneOf": [
            {
              "enum": ["arm64", "amd64"]
            }
          ]
        }
      ]
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-_]+$"
    },
    "tipi_version": {
      "type": "integer"
    },
    "version": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "short_desc": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "source": {
      "type": "string",
      "format": "url"
    },
    "website": {
      "type": "string",
      "format": "url"
    },
    "url_suffix": {
      "type": "string",
      "pattern": "^/[a-z0-9-_/]+$"
    },
    "form_fields": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {
              "type": "string",
              "oneOf": [
                {
                  "enum": [
                    "text",
                    "password",
                    "email",
                    "number",
                    "fqdn",
                    "ip",
                    "fqdnip",
                    "random",
                    "boolean"
                  ]
                }
              ]
            },
            "label": {
              "type": "string"
            },
            "max": {
              "type": "integer"
            },
            "min": {
              "type": "integer"
            },
            "required": {
              "type": "boolean"
            },
            "env_variable": {
              "type": "string"
            },
            "hint": {
              "type": "string"
            },
            "pleaceholder": {
              "type": "string"
            },
            "regex": {
              "type": "string"
            },
            "default": {
              "type": "string"
            },
            "pattern_error": {
              "type": "string"
            },
            "options": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "label": {
                    "type": "string",
                    "label": "string"
                  }
                }
              }
            }
          },
          "required": ["type", "label", "env_variable"]
        }
      ]
    },
    "dynamic_config": {
      "type": "boolean"
    },
    "min_tipi_version": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "available",
    "id",
    "tipi_version",
    "version",
    "categories",
    "description",
    "short_desc",
    "author",
    "source",
    "form_fields",
    "port",
    "dynamic_config"
  ]
}

=== runtipi/appstore/apps/nextcloud/config.json
{
  "$schema": "../app-config-schema.json",
  "name": "Nextcloud",
  "id": "nextcloud",
  "available": true,
  "short_desc": "Nextcloud server, a safe home for all your data.",
  "author": "nextcloud",
  "port": 8745,
  "categories": ["data"],
  "description": "Store your files, contacts, calendars, conversations and more on a server of your choosing.",
  "tipi_version": 1,
  "version": "29.0.1",
  "source": "https://github.com/nextcloud/server",
  "website": "https://nextcloud.com",
  "exposable": true,
  "supported_architectures": ["arm64", "amd64"],
  "form_fields": [
    {
      "type": "text",
      "label": "Nextcloud admin username",
      "required": true,
      "env_variable": "NEXTCLOUD_ADMIN_USER"
    },
    {
      "type": "password",
      "label": "Nextcloud admin password",
      "min": 8,
      "required": true,
      "env_variable": "NEXTCLOUD_ADMIN_PASSWORD"
    },
    {
      "type": "random",
      "label": "Nextcloud database password",
      "min": 32,
      "env_variable": "NEXTCLOUD_DB_PASSWORD"
    }
  ],
  "dynamic_config": true
}

=== runtipi/appstore/apps/adguard/config.json
{
  "$schema": "../app-config-schema.json",
  "name": "Adguard",
  "id": "adguard",
  "available": true,
  "short_desc": "Network-wide ads & trackers blocking DNS server.",
  "author": "AdguardTeam",
  "port": 8567,
  "categories": ["network"],
  "description": "AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover ALL your home devices, and you don't need any client-side software for that.",
  "tipi_version": 1,
  "version": "v0.107.50",
  "source": "https://github.com/AdguardTeam/AdGuardHome",
  "exposable": true,
  "supported_architectures": ["arm64", "amd64"],
  "form_fields": [],
  "dynamic_config": true
}

=== runtipi/appstore/apps/onedev/config.json
{
  "$schema": "../app-config-schema.json",
  "name": "Onedev",
  "id": "onedev",
  "available": true,
  "short_desc": "Git Server with CI/CD, Kanban, and Packages.",
  "author": "theonedev",
  "port": 6610,
  "categories": ["development"],
  "description": "Git Server with CI/CD, Kanban, and Packages. Seamless integration. Unparalleled experience.",
  "tipi_version": 1,
  "version": "10.8.0",
  "source": "https://code.onedev.io",
  "website": "https://onedev.io",
  "exposable": true,
  "supported_architectures": ["arm64", "amd64"],
  "form_fields": [],
  "dynamic_config": true
}
